version: "3.9"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: fo39ajf3
      MYSQL_DATABASE: todoApp
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    ports:
      - "3301:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

# mariadb -u root -p"fo39ajf3"

# root fo39ajf3

# php -S localhost:8000 -t src

